---
- hosts: localhost
  become: yes
  vars:
    parent_dir: "{{ playbook_dir | dirname }}"
    venv_path: "{{ parent_dir }}/venv"
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Add the UbuntuGIS unstable repository
      apt_repository:
        repo: ppa:ubuntugis/ubuntugis-unstable

    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install apt packages
      apt:
        name: "{{ item }}"
      loop:
        - grass

    - name: Ensure Python3 and venv are installed
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip

    - name: Create a virtual environment
      shell: "python3 -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}"

    - name: Install pip packages in virtual environment
      pip:
        virtualenv: "{{ venv_path }}"
        name: "{{ item }}"
      loop:
        - earthengine-api
        - grass-session
        - python-dotenv
        - pytest
        - geemap